#!/bin/sh

. /usr/share/libubox/jshn.sh

get_mesh_ip () {
    json_init

    interfaces=$(brctl showstp br-lan | awk '/ath13\.sta[0-9]+/ {print $1}')
    mode=$(uci -q get device.info.router_mode)
    if [ -z "$interfaces" ]; then
        json_add_string error "No ath13.staX interfaces found"
        json_close_object
        json_dump
        return
    fi

    json_add_array interfaces
    for interface in $interfaces; do
        json_add_object ""
        json_add_string name "$interface"
        json_add_string mode "$mode"

        mesh_2g_ssid=$(uci -q get wireless.mesh_2g.ssid)
        mesh_5g_ssid=$(uci -q get wireless.mesh_5g.ssid)

        if [ "X$mesh_2g_ssid" = "X$mesh_5g_ssid" ]; then
            json_add_string ssid "$mesh_2g_ssid"
        else
            json_add_string ssid24g "$mesh_2g_ssid"
            json_add_string ssid5g "$mesh_5g_ssid"
        fi

        port=$(brctl showstp br-lan | grep "$interface" | awk -F'[()]' '{print $2}')
        json_add_int port "$port"

        json_add_array connections
        macs=$(brctl showmacs br-lan | awk -v port=$port '$1 == port {print $2}')
        for mac in $macs; do
            json_add_object ""
            json_add_string mac "$mac"

            json_add_array ip
            ip_list=$(ip neigh show | grep "$mac" | awk '{print $1}')
            for ip in $ip_list; do
                json_add_string "" "$ip"
            done
            json_close_array

            json_close_object
        done
        json_close_array

        json_close_object
    done
    json_close_array
    json_close_object
    json_dump
}

get_mesh_ip